-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS  Kayttaja CASCADE;
DROP TABLE IF EXISTS Luokka CASCADE;
DROP TABLE IF EXISTS Tehtava CASCADE;
DROP TABLE IF EXISTS Kayttajantehtavat CASCADE;
DROP TABLE IF EXISTS Luokantehtavat CASCADE;
DROP TABLE IF EXISTS Luokanluokat CASCADE;